#!/bin/sh

PRJ_NAME="ImageCompressionWeb"

cd /zserver/java-projects/ZCommMedia/$PRJ_NAME/
/zserver/node-v16.15.1-linux-x64/bin/npm install
/zserver/node-v16.15.1-linux-x64/bin/node /zserver/java-projects/ZCommMedia/$PRJ_NAME/app.js
